version: "2"
services:
  db-for-dev:
    image: 'postgres:latest'
    container_name: customers
    environment:
      - POSTGRES_DB=customers_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"
    command: -p 5433
  db-for-tests:
    image: 'postgres:latest'
    container_name: customers_test
    environment:
      - POSTGRES_DB=customers_test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"